<div style='color: #216969;
           background-color: #EAF6F6;
           font-size: 200%;
           border-radius:15px;
           text-align:center;
           font-weight:600;
           border-style: solid;
           border-color: dark green;
           font-family: "Cambria";'>
Selection Best features  ....
<a class="anchor" id="1"></a>

<img src="https://miro.medium.com/max/594/1*nyC9bOwnK16Cl8jFYTyEFQ.png" width=400>

- Data loading
- Data Imputation
- Lasso deployement 
= Model Evaluation


https://youtu.be/T4nZDuakYlU?list=PLO_fdPEVlfKqMDNmCFzQISI2H_nJcEDJq

https://youtu.be/xlHk4okO8Ls

https://towardsdatascience.com/feature-selection-in-python-recursive-feature-elimination-19f1c39b8d15

https://github.com/Yimeng-Zhang/feature-engineering-and-feature-selection/blob/master/4.5_Demo_Feature_Selection_Hybrid_method.ipynb

Lasso Regression (L1 Regularization)

What it is: Lasso (Least Absolute Shrinkage and Selection Operator) regression is a linear regression technique that adds a penalty term to the ordinary least squares (OLS) cost function. This penalty is proportional to the absolute value of the coefficients.   

Why it's used:

Regularization: The penalty term shrinks the coefficients of less important features towards zero. This helps prevent overfitting, especially when you have many features or when some features are highly correlated.
Feature Selection: A key feature of Lasso is that it can force some coefficients to become exactly zero. This effectively performs feature selection, automatically identifying and discarding irrelevant features. This is different from Ridge regression (L2 regularization), which shrinks coefficients but rarely sets them to zero.
The Cost Function: The cost function Lasso minimizes is:

RSS + alpha * sum(|beta_j|)
 Where:

RSS is the residual sum of squares (the standard OLS term).
alpha is the regularization parameter (a hyperparameter you need to tune). A higher alpha means stronger regularization (more shrinkage and more coefficients set to zero).
beta_j are the regression coefficients.
sum(|beta_j|) is the sum of the absolute values of the coefficients (the L1 penalty).
2. Cross-Validation (CV)

What it is: Cross-validation is a technique for evaluating how well a model will generalize to unseen data. It involves splitting the data into multiple "folds," training the model on some folds (the training set), and evaluating it on the remaining fold (the validation set). This is repeated multiple times, with each fold serving as the validation set once.
Why it's used: It provides a more reliable estimate of model performance than a single train/test split, especially when you have limited data. It helps you choose the best hyperparameters (like alpha in Lasso) without "peeking" at the final test set.
Common Types:
k-fold Cross-Validation: The data is divided into k folds.
Leave-One-Out Cross-Validation (LOOCV): Each data point is used as the validation set once (extreme case of k-fold where k = number of samples).
Stratified k-fold: Ensures that each fold has roughly the same proportion of samples from each class (important for classification problems with imbalanced classes).
3. LassoCV in scikit-learn

sklearn.linear_model.LassoCV: This class in scikit-learn combines Lasso regression with cross-validation to automatically find the best value of the regularization parameter (alpha).
cv parameter:: Determines the cross-validation splitting strategy. If None, to use the default 5-fold cross-validation.
alphas parameter:: List of alphas where to compute the models. If None alphas are set automatically.

In [1]:
#تحميل البيانات
import pandas as pd
df= pd.read_csv("../data/HousePrice3.csv", index_col=0)

In [2]:
df.sample(3)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
617,618,45,RL,59.0,7227,Pave,NaN,Reg,HLS,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,105500
1443,1444,30,RL,NaN,8854,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2009,WD,Normal,121000
194,195,20,RL,60.0,7180,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2008,WD,Normal,127000

![](../imgs/featureEngin.png)

## Conduct Recursive Feature Elimination

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1460 entries, 0 to 1459
Data columns (total 78 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  2ndFlrSF       1460 non-null   int64
 44  LowQualFinSF   1460 non-null   int64
 45  GrLivArea      1460 non-null   int64
 46  BsmtFullBath   1460 non-null   int64
 47  BsmtHalfBath   1460 non-null   int64
 48  FullBath       1460 non-null   int64
 49  HalfBath       1460 non-null   int64
 50  BedroomAbvGr   1460 non-null   int64
 51  KitchenAbvGr   1460 non-null   int64
 52  KitchenQual    1460 non-null   object
 53  TotRmsAbvGrd   1460 non-null   int64
 54  Functional     1460 non-null   object
 55  Fireplaces     1460 non-null   int64
 56  FireplaceQu    770 non-null    object
 57  GarageType     1379 non-null   object
 58  GarageFinish   1379 non-null   object
 59  GarageArea     1460 non-null   int64
 60  GarageQual     1379 non-null   object
 61  GarageCond     1379 non-null   object
 62  PavedDrive     1460 non-null   object
 63  WoodDeckSF     1460 non-null   int64
 64  OpenPorchSF    1460 non-null   int64
 65  EnclosedPorch  1460 non-null   int64
 66  3SsnPorch      1460 non-null   int64
 67  ScreenPorch    1460 non-null   int64
 68  PoolArea       1460 non-null   int64
 69  PoolQC         7 non-null      object
 70  Fence          281 non-null    object
 71  MiscFeature    54 non-null     object
 72  MiscVal        1460 non-null   int64
 73  MoSold         1460 non-null   int64
 74  YrSold         1460 non-null   int64
 75  SaleType       1460 non-null   object
 76  SaleCondition  1460 non-null   object
 77  SalePrice      1460 non-null   int64
dtypes: float64(2), int64(33), object(43)
memory usage: 901.1+ KB

In [4]:
df.select_dtypes("number").head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [5]:
df.isna().sum().sort_values(ascending=False)

PoolQC           1453
MiscFeature      1406
Alley            1369
Fence            1179
MasVnrType        872
                 ...
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
Length: 78, dtype: int64

In [6]:
df.select_dtypes("number").head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,61,0,0,0,0,0,2,2008,208500
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,298,0,0,0,0,0,0,5,2007,181500
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,42,0,0,0,0,0,9,2008,223500
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,35,272,0,0,0,0,2,2006,140000
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,192,84,0,0,0,0,0,12,2008,250000

In [7]:
# 1. Separate Numerical and Categorical Columns
from sklearn.impute import SimpleImputer
def preprocess_dataframe(df):

    numerical_cols = df.select_dtypes(include=['number']).columns
    categorical_cols = df.select_dtypes(include=['object']).columns  # Or exclude number

    # 2. Impute Missing Values (Numerical)
    if len(numerical_cols) > 0 :
        imputer_num = SimpleImputer(strategy='mean')  # Or 'median'
        df[numerical_cols] = imputer_num.fit_transform(df[numerical_cols])

    # 3. Handle Categorical Columns (One-Hot Encoding)
    if len(categorical_cols) > 0 :
        df = pd.get_dummies(df, columns=categorical_cols, dummy_na=True)  # dummy_na handles NaN in categorical

    return df

df = pd.DataFrame(preprocess_dataframe(df), index = df.index)

In [8]:
df.isna().sum().sort_values(ascending=False)

SaleCondition_nan    0
Id                   0
MSSubClass           0
LotFrontage          0
LotArea              0
                    ..
2ndFlrSF             0
TotalBsmtSF          0
BsmtUnfSF            0
BsmtFinSF2           0
BsmtFinSF1           0
Length: 329, dtype: int64

![](../imgs/dataSplit.jpg)

In [9]:

X=  df.select_dtypes("number").iloc[:,:-1]
y= df.SalePrice

In [10]:
X.shape , y.shape

((1460, 34), (1460,))

In [11]:
# تقسيم البيانات
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X, y  ,test_size=.33, random_state=42)

![](../imgs/model.png)

### freature Selection using RFECV.

In [13]:
from sklearn.feature_selection import RFECV, SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [16]:



def compare_feature_selection(X_train,y_train,  X_test , y_test, models=[LinearRegression(), RandomForestRegressor()], k_best=5, cv=5, random_state=42):
    """
    Compares feature selection methods (RFECV and SelectKBest) with different models.

    Args:
        X (pd.DataFrame): Feature matrix.
        y (pd.Series): Target variable.
        models (list): List of scikit-learn regression models.
        k_best (int): Number of features to select with SelectKBest.
        cv (int): Number of cross-validation folds for RFECV.
        random_state (int): Random state for reproducibility.

    Returns:
        pd.DataFrame: DataFrame containing model metrics for each feature selection method.
    """

    results = []


    for model in models:
        model_name = model.__class__.__name__

        # SelectKBest
        selector_kbest = SelectKBest(score_func=f_regression, k=k_best)
        X_train_kbest = selector_kbest.fit_transform(X_train, y_train)
        X_test_kbest = selector_kbest.transform(X_test)

        model.fit(X_train_kbest, y_train)
        y_pred_kbest = model.predict(X_test_kbest)
        mse_kbest = mean_squared_error(y_test, y_pred_kbest)
        r2_kbest = r2_score(y_test, y_pred_kbest)

        results.append({
            'Model': model_name,
            'Feature Selection': 'SelectKBest',
            'MSE': mse_kbest,
            'R2': r2_kbest
        })

        # RFECV
        rfecv = RFECV(estimator=model, step=1, cv=cv, scoring='neg_mean_squared_error')
        rfecv.fit(X_train, y_train)
        X_train_rfecv = rfecv.transform(X_train)
        X_test_rfecv = rfecv.transform(X_test)

        model.fit(X_train_rfecv, y_train)
        y_pred_rfecv = model.predict(X_test_rfecv)
        mse_rfecv = mean_squared_error(y_test, y_pred_rfecv)
        r2_rfecv = r2_score(y_test, y_pred_rfecv)

        results.append({
            'Model': model_name,
            'Feature Selection': 'RFECV',
            'MSE': mse_rfecv,
            'R2': r2_rfecv
        })

    return pd.DataFrame(results)


comparison_df = compare_feature_selection(X_train, y_train, X_test, y_test)
print(comparison_df)

                   Model Feature Selection           MSE        R2
0       LinearRegression       SelectKBest  1.584770e+09  0.784132
1       LinearRegression             RFECV  1.852543e+09  0.747658
2  RandomForestRegressor       SelectKBest  1.274966e+09  0.826332
3  RandomForestRegressor             RFECV  9.383828e+08  0.872179